// Spanish catalog: normalized English source -> Spanish.
// First draft machine-authored and developer-reviewed; native-speaker
// review is welcome and rough edges deserve bug reports. Regenerate the
// key list with: node tools/extract-strings.mjs
// Missing entries fall back to English by design.
export const es = {
  "Home": "Casa",
  "The fountain": "La fuente",
  "coffee run": "por un café",
  "phone's dying": "sin batería ya",
  "omw to the fountain": "voy a la fuente",
  "made it": "llegué",
  "You": "Tú",
  "1 hr": "1 h",
  "1 min": "1 min",
  "5 min": "5 min",
  "A circle holds {n} people and yours is full. Remove somebody before letting anyone else in.": "Un círculo tiene espacio para {n} personas y el tuyo está lleno. Elimina a alguien antes de dejar entrar a otra persona.",
  "A few words your circle sees next to your name. It is encrypted like everything else, and it clears when you stop sharing.": "Unas palabras que tu círculo ve junto a tu nombre. Está cifrado como todo lo demás, y se borra cuando dejas de compartir.",
  "A member": "Un miembro",
  "A member's keys changed": "Las claves de un miembro cambiaron",
  "A relay must be an https URL, like https://relay.example.org": "El relay debe ser una URL https, como https://relay.example.org",
  "A second passcode for a moment when someone makes you open Starling. Entering it on the lock screen erases everything on this device, instantly and silently, and shows a fresh install. There is no undo and no way back in. It only guards the passcode path: biometric unlock still opens the app normally, so if a forced unlock is in your threat model, turn biometrics off too.": "Un segundo código de acceso para cuando alguien te obliga a abrir Starling. Escribirlo en la pantalla de bloqueo borra todo en este dispositivo, al instante y sin avisar, y muestra una instalación nueva. No hay forma de deshacerlo ni de volver atrás. Solo protege el camino del código de acceso: el desbloqueo biométrico sigue abriendo la app con normalidad, así que si un desbloqueo forzado forma parte de tu modelo de amenazas, desactiva también la biometría.",
  "A welcome arrived that did not match the person this link came from, and it was refused. That can be an interception attempt, or just a stale retry or a network hiccup. Your request is still waiting for the person who actually invited you; check with them before using the link again.": "Llegó un mensaje de bienvenida que no coincidía con la persona de la que venía este enlace, y se rechazó. Puede ser un intento de interceptación, o solo un reintento antiguo o un fallo de red. Tu solicitud sigue esperando a la persona que realmente te invitó: consúltalo con ella antes de volver a usar el enlace.",
  "A welcome that did not match the link's sender was refused. That can be an interception attempt, or just a stale retry. Check with whoever gave you the link before you use it again.": "Se rechazó un mensaje de bienvenida que no coincidía con quien envió el enlace. Puede ser un intento de interceptación, o solo un reintento antiguo. Consúltalo con quien te dio el enlace antes de volver a usarlo.",
  "Accept the new keys": "Aceptar las claves nuevas",
  "Accepting gives the whole circle new keys and lets them see everyone's location from then on. They cannot read anything sent before.": "Aceptar le da al círculo entero claves nuevas y les permite ver la ubicación de todos a partir de ese momento. No pueden leer nada enviado antes.",
  "Add Starling to your home screen": "Añade Starling a tu pantalla de inicio",
  "Another link, for one more person": "Otro enlace, para una persona más",
  "Anyone who checks this phone's storage can see that a duress code exists, though not what it is. What they cannot do is tell it apart from your real passcode while typing.": "Cualquiera que revise el almacenamiento de este teléfono puede ver que existe un código de coacción, aunque no cuál es. Lo que no puede hacer es distinguirlo de tu código de acceso real mientras lo escribes.",
  "Anyone you send one of these to can watch your live location on any phone or computer, with no app and no account. A link shows this emergency only, never your circle, and never the other links.": "Cualquiera a quien le envíes uno de estos puede ver tu ubicación en vivo desde cualquier teléfono u ordenador, sin app y sin cuenta. Un enlace muestra solo esta emergencia, nunca tu círculo, y nunca los otros enlaces.",
  "App lock is off.": "El bloqueo de la app está desactivado.",
  "App lock is on.": "El bloqueo de la app está activado.",
  "Arrive and leave alerts": "Avisos de llegada y salida",
  "Ask to join": "Pedir unirse",
  "At {place}": "En {place}",
  "Auto": "Auto",
  "Auto-lock": "Bloqueo automático",
  "Avatar {em}": "Avatar {em}",
  "Basemap": "Mapa base",
  "Battery {pct} percent": "Batería al {pct} por ciento",
  "Biometric unlock did not work. Use your passcode.": "El desbloqueo biométrico no funcionó. Usa tu código de acceso.",
  "Biometric unlock is off.": "El desbloqueo biométrico está desactivado.",
  "Cancel the request": "Cancelar la solicitud",
  "Cancel this link": "Cancelar este enlace",
  "Center the map on me": "Centrar el mapa en mí",
  "Change passcode": "Cambiar código de acceso",
  "Check": "Comprobar",
  "Check again": "Comprobar de nuevo",
  "Check in with your circle": "Avisar a tu círculo",
  "Check the numbers": "Comprueba los números",
  "Check their safety number with them first. Accepting is what lets them see everyone's location.": "Comprueba primero su número de seguridad con ellos. Aceptar es lo que les permite ver la ubicación de todos.",
  "Check {who}'s number": "Comprobar el número de {who}",
  "Check-in failed. Reconnecting...": "No se pudo avisar. Reconectando...",
  "Checked in": "Avisado",
  "Choose a passcode to lock Starling on this device. There is no reset: if you forget it you erase this device and rejoin from an invite.": "Elige un código de acceso para bloquear Starling en este dispositivo. No hay forma de restablecerlo: si lo olvidas, tienes que borrar este dispositivo y volver a unirte con una invitación.",
  "Circle name": "Nombre del círculo",
  "Clear status": "Borrar estado",
  "Close": "Cerrar",
  "Close member card": "Cerrar la tarjeta del miembro",
  "Compare in person": "Comparar en persona",
  "Connected": "Conectado",
  "Continue": "Continuar",
  "Coordinates copied": "Coordenadas copiadas",
  "Copy": "Copiar",
  "Copy coordinates": "Copiar coordenadas",
  "Copy failed": "No se pudo copiar",
  "Copy failed. Long-press the link instead.": "No se pudo copiar. Mantén pulsado el enlace en su lugar.",
  "Copy link": "Copiar enlace",
  "Could not cancel the link. Try again.": "No se pudo cancelar el enlace. Inténtalo de nuevo.",
  "Could not change the Orbot setting.": "No se pudo cambiar el ajuste de Orbot.",
  "Could not join. Try again.": "No fue posible unirse. Inténtalo de nuevo.",
  "Could not leave. Try again.": "No se pudo salir. Inténtalo de nuevo.",
  "Could not let them in. Try again.": "No se pudo dejarlos entrar. Inténtalo de nuevo.",
  "Could not make an invite link. Try again.": "No se pudo crear el enlace de invitación. Inténtalo de nuevo.",
  "Could not make another link.": "No se pudo crear otro enlace.",
  "Could not make new keys right now. Try again in a moment.": "No se pudieron generar claves nuevas ahora. Inténtalo de nuevo en un momento.",
  "Could not make new keys. Try again.": "No se pudieron generar claves nuevas. Inténtalo de nuevo.",
  "Could not reach anyone with the new keys. Nothing changed.": "No se pudo contactar a nadie con las claves nuevas. Nada cambió.",
  "Could not reach the relay to check the time.": "No se pudo contactar al relay para comprobar la hora.",
  "Could not reach them to send the keys, so nobody was let in. Try again in a moment.": "No se los pudo contactar para enviarles las claves, así que no se dejó entrar a nadie. Inténtalo de nuevo en un momento.",
  "Could not remove them. Nothing changed.": "No se pudo eliminarlos. Nada cambió.",
  "Could not save. Try again.": "No se pudo guardar. Inténtalo de nuevo.",
  "Could not send them the keys, so nobody was let in. Your link still works, so try again.": "No se les pudieron enviar las claves, así que no se dejó entrar a nadie. Tu enlace todavía funciona, así que inténtalo de nuevo.",
  "Could not send {who} the keys, and could not undo letting them in. Remove them from the circle before you try again.": "No se le pudieron enviar las claves a {who}, y no se pudo deshacer haberlo dejado entrar. Elimínalo del círculo antes de volver a intentarlo.",
  "Could not switch. Try again.": "No se pudo cambiar. Inténtalo de nuevo.",
  "Create a circle": "Crear un círculo",
  "Create circle": "Crear círculo",
  "Current": "Actual",
  "Dark": "Oscuro",
  "Demo circle": "Círculo de demostración",
  "Demo flight - nothing is real": "Vuelo de demostración: nada es real",
  "Directions": "Cómo llegar",
  "Done": "Listo",
  "Duress passcode removed.": "Código de coacción eliminado.",
  "Duress passcode saved.": "Código de coacción guardado.",
  "Encrypts your circle secret on this device. Nobody can open Starling, or read the secret from storage, without your passcode.": "Cifra el secreto de tu círculo en este dispositivo. Nadie puede abrir Starling, ni leer el secreto del almacenamiento, sin tu código de acceso.",
  "End-to-end encrypted. No accounts. Open protocol.": "Cifrado de extremo a extremo. Sin cuentas. Protocolo abierto.",
  "End-to-end encrypted. The relay sees ciphertext only.": "Cifrado de extremo a extremo. El relay solo ve texto cifrado.",
  "English is the app's source language. Translations come from the community; rough edges are worth reporting.": "El inglés es el idioma de origen de la app. Las traducciones vienen de la comunidad: si encuentras algo raro, vale la pena reportarlo.",
  "Enter your passcode to open your circle.": "Escribe tu código de acceso para abrir tu círculo.",
  "Enter your passcode to stop encrypting the circle secret at rest.": "Escribe tu código de acceso para dejar de cifrar el secreto del círculo en reposo.",
  "Erase and start over": "Borrar y empezar de nuevo",
  "Erases the circle secret, your identity, and all Starling data from this device, then reloads. One residual: street-map tiles your browser cached may remain in its own cache. The Off-grid basemap never loads any. There is no undo. Hold the button to confirm.": "Borra el secreto del círculo, tu identidad y todos los datos de Starling de este dispositivo, y luego recarga. Queda un resto: los mosaicos del mapa de calles que tu navegador haya guardado pueden quedar en su propia caché. El mapa base Fuera de red nunca carga ninguno. No hay forma de deshacerlo. Mantén pulsado el botón para confirmar.",
  "Every link stops updating and shows that the session ended. A new SOS makes new links.": "Todos los enlaces dejan de actualizarse y muestran que la sesión terminó. Un nuevo SOS crea enlaces nuevos.",
  "Everyone here is checked": "Todos aquí están comprobados",
  "Everyone in the circle gets a fresh key and the old one stops working, so anybody holding a copy of the old one goes dark. Do this if a phone in the circle was taken, unlocked, or handed over. Nobody is removed and nothing on your map disappears.": "Todos en el círculo reciben una clave nueva y la anterior deja de funcionar, así que cualquiera que tenga una copia de la vieja se queda a oscuras. Haz esto si a alguien del círculo le quitaron el teléfono, se lo desbloquearon o lo entregaron. No se elimina a nadie y nada desaparece de tu mapa.",
  "Everyone in this circle, their safety numbers, and who you have checked.": "Todos los miembros de este círculo, sus números de seguridad y a quién has comprobado.",
  "Exit": "Salir",
  "Exit the demo first.": "Sal de la demostración primero.",
  "Exit the demo to edit your places.": "Sal de la demostración para editar tus lugares.",
  "Exit the demo to invite your people.": "Sal de la demostración para invitar a tu gente.",
  "Exit the demo to see your circle's keys.": "Sal de la demostración para ver las claves de tu círculo.",
  "Exit the demo to set a status.": "Sal de la demostración para poner un estado.",
  "Expand or collapse the circle sheet": "Expandir o contraer el panel del círculo",
  "Expires in {left}": "Expira en {left}",
  "Forgot passcode": "Olvidé mi código de acceso",
  "Get help from outside your circle": "Pide ayuda desde fuera de tu círculo",
  "Get outside help": "Pedir ayuda externa",
  "Get told when your people arrive": "Entérate cuando llegue tu gente",
  "Give the place a name first.": "Ponle un nombre al lugar primero.",
  "Got it": "Entendido",
  "Help link": "Enlace de ayuda",
  "Help links switched off": "Enlaces de ayuda desactivados",
  "Hold on, still finishing the last circle change.": "Espera, todavía estamos terminando el último cambio del círculo.",
  "Hold the phones side by side. Every group has to match.": "Sostén los teléfonos uno junto al otro. Todos los grupos tienen que coincidir.",
  "Hold to erase everything": "Mantén pulsado para borrar todo",
  "Hold to erase this device": "Mantén pulsado para borrar este dispositivo",
  "Hold to send SOS": "Mantén pulsado para enviar SOS",
  "Holds the screen on while the map is open": "Mantiene la pantalla encendida mientras el mapa está abierto",
  "How far back you can see": "Cuánto puedes ver hacia atrás",
  "How you appear to the people you invite. This never leaves your circle.": "Cómo apareces ante las personas que invitas. Esto nunca sale de tu círculo.",
  "I have an invite": "Tengo una invitación",
  "Invite link": "Enlace de invitación",
  "Invite link cleared from your clipboard.": "Enlace de invitación borrado del portapapeles.",
  "Invite people": "Invitar personas",
  "Invite someone": "Invitar a alguien",
  "Invite your people": "Invita a tu gente",
  "It is about {n} minutes {dir}.": "Va unos {n} minutos {dir}.",
  "Its keys are out of memory and nothing you send arrives any more, but this device could not delete them from its own storage, most likely because there is no room left. They are still on the disk. Free some space and open Starling again to finish clearing it, or use Panic to erase everything now.": "Sus claves ya no están en memoria y nada de lo que envíes llega, pero este dispositivo no pudo borrarlas de su propio almacenamiento, probablemente porque no queda espacio. Siguen en el disco. Libera algo de espacio y abre Starling de nuevo para terminar de borrarlas, o usa el borrado de pánico para borrar todo ahora.",
  "Join a circle": "Unirte a un círculo",
  "Join with a link": "Unirte con un enlace",
  "Join with invite": "Unirte con invitación",
  "Just you here so far": "Por ahora solo estás tú aquí",
  "Keep screen awake": "Mantener la pantalla encendida",
  "Keep this screen on": "Mantener esta pantalla encendida",
  "Keys changed. Check before you trust it.": "Las claves cambiaron. Compruébalo antes de confiar.",
  "Keys older than this window are destroyed on this device and cannot be brought back, by you or by anyone holding the phone.": "Las claves más viejas que esta ventana de tiempo se destruyen en este dispositivo y no se pueden recuperar, ni tú ni nadie que tenga el teléfono.",
  "Language": "Idioma",
  "Language saved. Reopen settings to see them translated too.": "Idioma guardado. Vuelve a abrir los ajustes para verlos traducidos también.",
  "Last seen": "Última vez visto",
  "Last update {ago}": "Última actualización: {ago}",
  "Leave circle": "Salir del círculo",
  "Leave this circle": "Salir de este círculo",
  "Light": "Claro",
  "Link cancelled. It cannot be used now.": "Enlace cancelado. Ya no se puede usar.",
  "Live": "En vivo",
  "Live · Neighborhood": "En vivo · Vecindario",
  "Live · Precise": "En vivo · Precisa",
  "Locating...": "Localizando...",
  "Location is blocked": "La ubicación está bloqueada",
  "Location is not available in this browser.": "La ubicación no está disponible en este navegador.",
  "Location needs HTTPS. Open the deployed app or localhost.": "La ubicación necesita HTTPS. Abre la app desplegada o localhost.",
  "Location permission is off for Starling. Open the app's settings, allow location, then come back and tap Start sharing.": "El permiso de ubicación está desactivado para Starling. Abre los ajustes de la app, permite la ubicación y luego vuelve y toca Empezar a compartir.",
  "Location stopped: {reason}": "Ubicación detenida: {reason}",
  "Locked": "Bloqueado",
  "Low battery alerts": "Avisos de batería baja",
  "Make another link": "Crear otro enlace",
  "Make new keys": "Generar claves nuevas",
  "Mark verified": "Marcar como verificado",
  "Member": "Miembro",
  "Name the spots that matter and hear about arrivals. Places never leave this phone.": "Ponle nombre a los lugares que importan y entérate de las llegadas. Lugares nunca sale de este teléfono.",
  "Name the spots that matter, like Home or School, and Starling tells you when someone in your circle arrives or leaves. Places are stored only on this phone. They are never sent anywhere, and the relay cannot learn they exist.": "Ponle nombre a los lugares que importan, como Casa o Escuela, y Starling te avisa cuando alguien de tu círculo llega o se va. Lugares se guarda solo en este teléfono. Nunca se envía a ningún sitio, y el relay no puede saber que existe.",
  "Neighborhood": "Vecindario",
  "Neighborhood rounds your position to about 1 km on your device before it is encrypted": "Vecindario redondea tu posición a aproximadamente 1 km en tu dispositivo antes de cifrarla",
  "New circle": "Círculo nuevo",
  "New keys now": "Claves nuevas ahora",
  "New keys were made while this device could not be reached, and they cannot be worked out from the old ones. Nothing you send now arrives. Ask somebody in the circle for a fresh invite link.": "Se generaron claves nuevas mientras no se podía contactar a este dispositivo, y no se pueden deducir a partir de las anteriores. Nada de lo que envíes ahora llega. Pídele a alguien del círculo un enlace de invitación nuevo.",
  "New link ready to send.": "Enlace nuevo listo para enviar.",
  "No location fix yet. Still trying...": "Todavía sin ubicación. Sigo intentando...",
  "No location yet. Start sharing to place yourself.": "Todavía sin ubicación. Empieza a compartir para ubicarte.",
  "No position yet. Start sharing first, or pick the spot on the map.": "Todavía sin posición. Empieza a compartir primero, o elige el punto en el mapa.",
  "No update from anyone in over {n} minutes. Usually that just means phones are asleep. But if others say they are sharing right now, this phone may have missed the circle's new keys; ask any member for a fresh invite to be sure.": "Nadie ha actualizado en más de {n} minutos. Normalmente eso solo significa que los teléfonos están en reposo. Pero si otros dicen que están compartiendo ahora mismo, puede que este teléfono se haya perdido las claves nuevas del círculo: pídele a cualquier miembro una invitación nueva para estar seguro.",
  "Nobody else in this circle yet": "Todavía nadie más en este círculo",
  "Nobody else is in this circle yet. Invite someone from the map.": "Todavía no hay nadie más en este círculo. Invita a alguien desde el mapa.",
  "Nobody has been heard from in a while": "Nadie ha dado señales de vida en un rato.",
  "Nobody has told you the circle's real name yet (names travel encrypted, like everything else), so pick whatever you will recognize. Rename it any time in settings.": "Todavía nadie te ha dicho el nombre real del círculo (los nombres viajan cifrados, como todo lo demás), así que elige algo que reconozcas. Puedes cambiarlo cuando quieras desde los ajustes.",
  "Not connected": "Sin conexión",
  "Not now": "Ahora no",
  "Not sharing": "Sin compartir",
  "Not visible: this phone's clock is wrong": "No visible: el reloj de este teléfono está mal",
  "Now": "Ahora",
  "Numbers match, let them in": "Los números coinciden, dejar entrar",
  "Off-grid": "Fuera de red",
  "One of your circles expired while this phone was away": "Uno de tus círculos expiró mientras este teléfono estaba desconectado",
  "One use only, and it expires in {left}. Accepting somebody uses it up.": "Solo se puede usar una vez, y expira en {left}. Aceptar a alguien lo gasta.",
  "Open Starling to check their number and let them in.": "Abre Starling para comprobar su número y dejarlo entrar.",
  "Open Starling to see their live position.": "Abre Starling para ver su posición en vivo.",
  "Open app settings": "Abrir ajustes de la app",
  "Open members": "Abrir miembros",
  "Or your own words": "O tus propias palabras",
  "Panic wipe": "Borrado de pánico",
  "Passcode": "Código de acceso",
  "Passcode changed.": "Código de acceso cambiado.",
  "Paste the invite link someone sent you. The circle secret stays in the link fragment and never touches a server.": "Pega el enlace de invitación que te enviaron. El secreto del círculo se queda en el fragmento del enlace y nunca toca un servidor.",
  "People and keys": "Personas y claves",
  "Pick an avatar": "Elige un avatar",
  "Pick on the map": "Elegir en el mapa",
  "Places": "Lugares",
  "Point Starling at your own relay if you run one. The relay source ships with the app, so anyone can host it. Leave this empty for the default. A change applies the next time Starling starts.": "Apunta Starling a tu propio relay si tienes uno. El código del relay viene con la app, así que cualquiera puede alojarlo. Déjalo vacío para usar el predeterminado. Un cambio se aplica la próxima vez que Starling arranque.",
  "Precise": "Precisa",
  "Precision": "Precisión",
  "Press and hold to send SOS": "Mantén presionado para enviar SOS",
  "Probably just quiet": "Probablemente solo está tranquilo",
  "Reconnecting": "Reconectando",
  "Reconnecting...": "Reconectando...",
  "Reject": "Rechazar",
  "Relay": "Relay",
  "Relay saved. It applies the next time Starling starts.": "Relay guardado. Se aplica la próxima vez que Starling arranque.",
  "Relock after the app has been in the background this long.": "Vuelve a bloquear después de que la app lleve tanto tiempo en segundo plano.",
  "Remove": "Eliminar",
  "Remove duress passcode": "Eliminar código de coacción",
  "Remove them": "Eliminarlo",
  "Remove {name}": "Eliminar a {name}",
  "Request sent. Someone in the circle has to accept it from their phone.": "Solicitud enviada. Alguien del círculo tiene que aceptarla desde su teléfono.",
  "Require passcode": "Requerir código de acceso",
  "Review the request": "Revisar la solicitud",
  "Revoke": "Revocar",
  "Route through Orbot": "Enrutar a través de Orbot",
  "SOS": "SOS",
  "SOS active": "SOS activo",
  "SOS armed · Locating...": "SOS armado · Localizando...",
  "SOS armed · Sharing live": "SOS armado · Compartiendo en vivo",
  "SOS failed to send. Reconnecting...": "No se pudo enviar el SOS. Reconectando...",
  "SOS from {who}": "SOS de {who}",
  "SOS is armed": "El SOS está armado",
  "SOS sent to your circle. Tap the check mark to cancel.": "SOS enviado a tu círculo. Toca la marca de verificación para cancelarlo.",
  "Safety number {digits}": "Número de seguridad {digits}",
  "Save duress passcode": "Guardar código de coacción",
  "Save my current spot": "Guardar mi ubicación actual",
  "Saved. Your circle sees it once you start sharing.": "Guardado. Tu círculo lo ve en cuanto empieces a compartir.",
  "See who is here": "Ver quién está aquí",
  "Send": "Enviar",
  "Send it through something you already trust, like Signal. Whoever opens it can ask to join; they are not in until you check their number and accept.": "Envíalo por algo en lo que ya confíes, como Signal. Quien lo abra puede pedir unirse: no entra hasta que compruebes su número y aceptes.",
  "Send on the timer even when you have not moved. The relay cannot read a position either way, but a burst of updates while you walk and silence while you sit is a movement trail made of timing alone. This hides that, and costs a little battery.": "Envía por temporizador incluso cuando no te has movido. El relay no puede leer la posición de todos modos, pero una ráfaga de actualizaciones mientras caminas y silencio mientras estás quieto forman un rastro de movimiento hecho solo de tiempos. Esto lo oculta, y cuesta un poco de batería.",
  "Send the link": "Enviar el enlace",
  "Sends relay and map traffic through Orbot's Tor proxy on this device. Needs Orbot installed with Power User Mode on. Orbot's per-app VPN mode also covers Starling with this off.": "Envía el tráfico del relay y del mapa a través del proxy Tor de Orbot en este dispositivo. Necesita tener Orbot instalado con \"Power User Mode\" activado. El modo VPN por app de Orbot también cubre a Starling aunque esto esté desactivado.",
  "Sent it to the wrong person?": "¿Se lo enviaste a la persona equivocada?",
  "Session ended": "Sesión terminada",
  "Set a passcode": "Elegir código de acceso",
  "Set a status for your circle": "Pon un estado para tu círculo",
  "Set status": "Poner estado",
  "Settings": "Ajustes",
  "Sharing live": "Compartiendo en vivo",
  "Sharing{run}, and this screen has to stay on": "Compartiendo{run}, y esta pantalla tiene que quedarse encendida",
  "Show recent paths on the map": "Mostrar rutas recientes en el mapa",
  "Signal lost": "Señal perdida",
  "Somebody already in that circle has to accept your request. Read them your number: {digits}{jumped}": "Alguien que ya esté en ese círculo tiene que aceptar tu solicitud. Léele tu número: {digits}{jumped}",
  "Somebody else is jamming that invite link, so it cannot be used any more. Nobody was let in. Make a new link and send it again.": "Alguien más está saturando ese enlace de invitación, así que ya no se puede usar. No se dejó entrar a nadie. Crea un enlace nuevo y envíalo de nuevo.",
  "Someone": "Alguien",
  "Someone wants to join": "Alguien quiere unirse",
  "Starling 0.7.1": "Starling 0.7.1",
  "Starling cannot recover a forgotten passcode. Nothing about your circle leaves your device unencrypted, so there is no reset link. You can erase this device and rejoin your circle from a fresh invite. Hold the button to erase everything on this device.": "Starling no puede recuperar un código de acceso olvidado. Nada de tu círculo sale de tu dispositivo sin cifrar, así que no hay enlace para restablecerlo. Puedes borrar este dispositivo y volver a unirte a tu círculo con una invitación nueva. Mantén pulsado el botón para borrar todo en este dispositivo.",
  "Starling hit a problem while starting.": "Starling tuvo un problema al iniciar.",
  "Starling only gets good when your people are on the map. Send them your invite link.": "Starling solo funciona bien cuando tu gente está en el mapa. Envíales tu enlace de invitación.",
  "Starling throws a circle's keys away rather than carry them for weeks, and that circle passed the point where this device could still read it, so it was erased from this phone. {kept} Ask somebody in that circle for a fresh invite link if you want back in.": "Starling descarta las claves de un círculo en vez de conservarlas durante semanas, y ese círculo pasó el punto en el que este dispositivo todavía podía leerlo, así que se borró de este teléfono. {kept} Pídele a alguien de ese círculo un enlace de invitación nuevo si quieres volver a entrar.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this device passed that point while it was away. Its keys are gone from memory and from storage, and so is this phone's own identity in that circle, so nothing you send arrives and nothing sent to you can be read. Ask somebody in the circle for a fresh invite link.": "Starling descarta las claves de un círculo en vez de conservarlas durante semanas, y este dispositivo pasó ese punto mientras estaba desconectado. Sus claves desaparecieron de la memoria y del almacenamiento, y también la identidad de este teléfono en ese círculo, así que nada de lo que envíes llega y nada de lo que te envíen se puede leer. Pídele a alguien del círculo un enlace de invitación nuevo.",
  "Starling throws a circle's keys away rather than carry them for weeks, and this phone passed that point while it was away. The circle was erased from this device, and there was no other circle to fall back to.{lockLine} Ask somebody for a fresh invite link, or start a new circle.": "Starling descarta las claves de un círculo en vez de conservarlas durante semanas, y este teléfono pasó ese punto mientras estaba desconectado. El círculo se borró de este dispositivo, y no había otro círculo al que recurrir.{lockLine} Pídele a alguien un enlace de invitación nuevo, o crea un círculo nuevo.",
  "Starling trusts whoever first answers with keys that match their member id. Reading these numbers out to each other is what turns that into knowing who is on your map.": "Starling confía en quien primero responda con claves que coincidan con su id de miembro. Leerse estos números en voz alta es lo que convierte eso en saber quién está en tu mapa.",
  "Start a new circle": "Crear un círculo nuevo",
  "Start fresh": "Empezar de cero",
  "Start sharing": "Empezar a compartir",
  "Steady sending": "Envío constante",
  "Steady sending is on too, so the relay cannot read your movement from the timing.": "El envío constante también está activado, así que el relay no puede leer tu movimiento a partir de los tiempos.",
  "Still about {n} minutes out.": "Todavía a unos {n} minutos.",
  "Stop sharing with helpers": "Dejar de compartir con los ayudantes",
  "Stopped": "Detenido",
  "Street maps load tiles from OpenStreetMap, which sees your map viewport. Off-grid loads nothing.": "Los mapas de calles cargan mosaicos desde OpenStreetMap, que ve el área visible de tu mapa. Fuera de red no carga nada.",
  "Switch circle": "Cambiar de círculo",
  "Switched to {name}.": "Cambiaste a {name}.",
  "Tap the map where {name} is.": "Toca el mapa donde está {name}.",
  "Tell me when a member's phone drops under 15 percent, before their dot goes dark": "Avísame cuando el teléfono de un miembro baje del 15 por ciento, antes de que su punto se apague",
  "Tell me when someone in the circle reaches a place or leaves one": "Avísame cuando alguien del círculo llegue a un lugar o salga de uno",
  "That circle expired, and this device could not erase all of it. Open Starling again to finish clearing it.": "Ese círculo expiró, y este dispositivo no pudo borrarlo por completo. Abre Starling de nuevo para terminar de borrarlo.",
  "That circle expired, and this phone could not erase it": "Ese círculo expiró, y este teléfono no pudo borrarlo",
  "That does not look like a Starling invite link.": "Eso no parece un enlace de invitación de Starling.",
  "That invitation arrived incomplete": "Esa invitación llegó incompleta",
  "That invitation expired. Make a new link.": "Esa invitación expiró. Crea un enlace nuevo.",
  "That is the lot: {n} places is the cap.": "Eso es todo: el límite es de {n} lugares.",
  "That is your duress passcode. Pick a different one.": "Ese es tu código de coacción. Elige uno diferente.",
  "That is your own invite link.": "Ese es tu propio enlace de invitación.",
  "That is your unlock passcode. A duress code has to be different.": "Ese es tu código de acceso normal. El código de coacción tiene que ser diferente.",
  "That link is dead. The others still work.": "Ese enlace ya no funciona. Los demás siguen funcionando.",
  "That passcode is right, but this install's stored data will not open. Nothing was erased.": "Ese código de acceso es correcto, pero los datos guardados de esta instalación no se abren. No se borró nada.",
  "That phone is answering with keys this device has never seen. It is a reinstall, or somebody else in {who}'s place, and nothing here can tell you which. Their location stays off your map until you check the number with them and accept it.": "Ese teléfono está respondiendo con claves que este dispositivo nunca ha visto. Es una reinstalación, o alguien más en el lugar de {who}, y nada aquí puede decirte cuál de las dos. Su ubicación se mantiene fuera de tu mapa hasta que compruebes el número con esa persona y lo aceptes.",
  "That request's keys are malformed. Nobody was let in.": "Las claves de esa solicitud están mal formadas. No se dejó entrar a nadie.",
  "The SOS is cleared.": "El SOS se canceló.",
  "The clock looks right now. Your circle can see you again.": "El reloj se ve bien ahora. Tu círculo puede verte de nuevo.",
  "The demo stays off-grid. Your choice applies when you exit.": "La demostración se queda fuera de red. Tu elección se aplica cuando salgas.",
  "The label is for you. It is never sent anywhere.": "La etiqueta es solo para ti. Nunca se envía a ningún sitio.",
  "The link stops working immediately, and any request already waiting on it is dropped. Open Invite again for a fresh one.": "El enlace deja de funcionar de inmediato, y cualquier solicitud que ya estuviera esperando se descarta. Abre Invitar de nuevo para conseguir uno nuevo.",
  "The relay that passes your updates along stores only encrypted data it cannot read, and deletes it after 24 hours. The protocol is open, so anyone can check these claims against the code.": "El relay que transmite tus actualizaciones solo guarda datos cifrados que no puede leer, y los borra después de 24 horas. El protocolo es abierto, así que cualquiera puede comprobar estas afirmaciones contra el código.",
  "Their dot may go dark soon.": "Es posible que su punto se apague pronto.",
  "Their number is {theirs}. Yours is {mine}. Read them to each other out loud, on a line you already trust. Nothing else in this circle has been checked by a person yet.": "Su número es {theirs}. El tuyo es {mine}. Léanselos en voz alta el uno al otro, por un canal en el que ya confíen. Nada más en este círculo ha sido comprobado por una persona todavía.",
  "Theme": "Tema",
  "They": "Ellos",
  "This browser is blocking storage. Starling runs, but nothing is saved after you close it.": "Este navegador está bloqueando el almacenamiento. Starling funciona, pero no se guarda nada después de cerrarlo.",
  "This is taking a while. The person who invited you may not have seen the request yet, or the link may have expired. Reach them however you normally would; a fresh link takes a minute to make.": "Esto está tardando. Puede que la persona que te invitó todavía no haya visto la solicitud, o que el enlace haya expirado. Contáctala como lo harías normalmente: crear un enlace nuevo toma un minuto.",
  "This is the number your circle should hear from you.": "Este es el número que tu círculo debería escuchar de ti.",
  "This phone has been offline too long": "Este teléfono ha estado desconectado demasiado tiempo",
  "This phone's clock is wrong": "El reloj de este teléfono está mal",
  "This phone's clock is wrong, so your circle cannot see you.{off} Turn on automatic date and time.": "El reloj de este teléfono está mal, así que tu círculo no puede verte.{off} Activa la fecha y hora automáticas.",
  "This sends a request. Somebody already in the circle has to check your safety number and accept it before you can see anyone, or they you. That check is how they know the request really came from you and not from somebody who got hold of the link.": "Esto envía una solicitud. Alguien que ya esté en el círculo tiene que comprobar tu número de seguridad y aceptarla antes de que puedas ver a nadie, ni ellos a ti. Esa comprobación es como saben que la solicitud realmente vino de ti y no de alguien que consiguió el enlace.",
  "Those keys are gone": "Esas claves ya no existen",
  "Those new keys are malformed. They were not accepted.": "Esas claves nuevas están mal formadas. No se aceptaron.",
  "Trail": "Rastro",
  "Trail history": "Historial de rastro",
  "Try again": "Inténtalo de nuevo",
  "Turn off app lock": "Desactivar el bloqueo de la app",
  "Turn on app lock": "Activar el bloqueo de la app",
  "Turned down. Your link still works for whoever it was meant for.": "Rechazada. Tu enlace todavía funciona para quien iba dirigido.",
  "Unlock": "Desbloquear",
  "Unlock with biometrics": "Desbloquear con biometría",
  "Unlocking...": "Desbloqueando...",
  "Update Starling": "Actualizar Starling",
  "Use at least {n} characters.": "Usa al menos {n} caracteres.",
  "Use this device's Face ID, fingerprint, or Windows Hello to unlock. Your passcode still works as backup.": "Usa el Face ID, la huella o Windows Hello de este dispositivo para desbloquear. Tu código de acceso sigue funcionando como respaldo.",
  "Waiting to be let into {name}": "Esperando a que te dejen entrar a {name}",
  "Was": "Antes",
  "Watch the demo": "Ver la demostración",
  "What Starling is and how it works &#8599;": "Qué es Starling y cómo funciona &#8599;",
  "When you are safe": "Cuando estés a salvo",
  "Wrong passcode. Try again.": "Código de acceso incorrecto. Inténtalo de nuevo.",
  "You already asked to join. They still have to let you in.": "Ya pediste unirte. Todavía tienen que dejarte entrar.",
  "You have an invite to a circle. Set up how you will appear to the people in it.": "Tienes una invitación a un círculo. Configura cómo aparecerás ante las personas que están en él.",
  "You have checked this number with {who}.": "Has comprobado este número con {who}.",
  "You joined the circle.": "Te uniste al círculo.",
  "You left. Now in {name}.": "Saliste. Ahora estás en {name}.",
  "You're in": "Ya estás dentro",
  "Your app lock and your other circles were not touched.": "Tu bloqueo de la app y tus otros círculos no se tocaron.",
  "Your app lock is untouched and still protects whatever you set up next.": "Tu bloqueo de la app sigue intacto y sigue protegiendo lo que configures a continuación.",
  "Your browser is blocking location for this site. Allow location in your browser's site settings, then tap Start sharing again.": "Tu navegador está bloqueando la ubicación para este sitio. Permite la ubicación en los ajustes del sitio de tu navegador, y luego toca Empezar a compartir de nuevo.",
  "Your circle cannot see you. The relay refuses anything stamped with a time that far out, so your position is not going anywhere.{off} Turn on automatic date and time, then check again.": "Tu círculo no puede verte. El relay rechaza cualquier cosa marcada con una hora tan desfasada, así que tu posición no va a ningún lado.{off} Activa la fecha y hora automáticas, y luego comprueba de nuevo.",
  "Your circle has new keys, but they could not be saved. If Starling restarts you will need a fresh invitation.": "Tu círculo tiene claves nuevas, pero no se pudieron guardar. Si Starling se reinicia, necesitarás una invitación nueva.",
  "Your circle has new keys.": "Tu círculo tiene claves nuevas.",
  "Your circle moved on without this phone": "Tu círculo siguió adelante sin este teléfono",
  "Your circle sees an alert at your live position. Tap the check mark above to cancel it and let everyone know you are okay.": "Tu círculo ve una alerta en tu posición en vivo. Toca la marca de verificación de arriba para cancelarla y avisarles a todos que estás bien.",
  "Your circles": "Tus círculos",
  "Your current circle stays. This adds a new one, and you can switch between them from the circle name at the top of the map.": "Tu círculo actual se mantiene. Esto añade uno nuevo, y puedes cambiar entre ellos desde el nombre del círculo en la parte superior del mapa.",
  "Your list of members does not match": "Tu lista de miembros no coincide",
  "Your name": "Tu nombre",
  "Your number": "Tu número",
  "Your other circles": "Tus otros círculos",
  "Your other circles could not be read and were dropped.": "Tus otros círculos no se pudieron leer y se descartaron.",
  "Your other circles were not touched.": "Tus otros círculos no se tocaron.",
  "Your people, on your map. Nobody else.": "Tu gente, en tu mapa. Nadie más.",
  "Your positions are encrypted on this device with a key only your circle holds. There are no accounts, no phone numbers, and no server that can read where you are. Sharing is off until you turn it on, and stopping is one tap.": "Tus posiciones se cifran en este dispositivo con una clave que solo tiene tu círculo. No hay cuentas, ni números de teléfono, ni ningún servidor que pueda leer dónde estás. Compartir está desactivado hasta que lo actives, y detenerlo es un solo toque.",
  "Your request is waiting on the relay. Somebody already in the circle has to check your number and accept it, and they do not have to be online right now.": "Tu solicitud está esperando en el relay. Alguien que ya esté en el círculo tiene que comprobar tu número y aceptarlo, y no hace falta que esté conectado ahora mismo.",
  "Your request was accepted. Your circle is on the map.": "Tu solicitud fue aceptada. Tu círculo está en el mapa.",
  "Your status": "Tu estado",
  "a member": "un miembro",
  "ahead": "de adelanto",
  "behind": "de atraso",
  "for {t}": "durante {t}",
  "not available": "no disponible",
  "not ready yet": "todavía no está listo",
  "now": "ahora",
  "service error": "error del servicio",
  "starling": "starling",
  "the person who let you in": "la persona que te dejó entrar",
  "them": "ellos",
  "{failed} of {total} members did not get the new keys yet.": "{failed} de {total} miembros aún no tienen las claves nuevas.",
  "{name} radius": "Radio de {name}",
  "{name} saved. Only this phone knows it exists.": "{name} guardado. Solo este teléfono sabe que existe.",
  "{n} members' keys changed": "Las claves de {n} miembros cambiaron",
  "{who} arrived at {place}": "{who} llegó a {place}",
  "{who} can read nothing this circle sends from now on. Everyone still here got new keys.": "{who} no puede leer nada de lo que este círculo envíe a partir de ahora. Todos los que siguen aquí tienen claves nuevas.",
  "{who} changed the keys": "{who} cambió las claves",
  "{who} changed the keys.": "{who} cambió las claves.",
  "{who} checked in": "{who} avisó",
  "{who} is now pinned to the new keys.": "Las claves nuevas quedaron ancladas a {who}.",
  "{who} is out. Everyone else has new keys.": "{who} está fuera. Todos los demás tienen claves nuevas.",
  "{who} joined. Everyone got new keys.": "{who} se unió. Todos recibieron claves nuevas.",
  "{who} left {place}": "{who} salió de {place}",
  "{who} made new keys, but your list of members does not match theirs.": "{who} generó claves nuevas, pero tu lista de miembros no coincide con la suya.",
  "{who} removed {gone}": "{who} eliminó a {gone}",
  "{who} removed {gone}.": "{who} eliminó a {gone}.",
  "{who} removed {n} people": "{who} eliminó a {n} personas",
  "{who} removed {n} people from the circle.": "{who} eliminó a {n} personas del círculo.",
  "{who} wants to join": "{who} quiere unirse",
  "{who} wants to join. Check their safety number.": "{who} quiere unirse. Comprueba su número de seguridad.",
  "{who}'s keys changed": "Las claves de {who} cambiaron",
  "{who}'s keys changed. Their location is hidden until you accept it.": "Las claves de {who} cambiaron. Su ubicación está oculta hasta que lo aceptes.",
  "{who}'s phone is at {pct}%": "El teléfono de {who} está al {pct}%",
};
